[function]
fn1 = { restart = "devsm-tui" }

[service.devsm]
pwd = "tests/workspace"
cmd = ["cargo", "run", "--", "self", "server"]
env.DEVSM_SOCKET = "/tmp/.devsm.test.socket"
env.DEVSM_LOG_STDOUT = "1"
ready.when.output_contains = "RPC Socket bound"
ready.timeout = 5.0
cache.never = true

[action.devsm-tui]
pwd = "tests/workspace"
cmd = ["/tmp/rust-target/debug/devsm"]
env.DEVSM_SOCKET = "/tmp/.devsm.test.socket"
env.DEVSM_NO_AUTO_SPAWN = "1"
require = ["devsm"]
managed = "terminal"
sticky = true

[test.taplo-validate-json-schema]
sh = """
taplo validate --schema "file://$(realpath schema/devsm.json)" ./schema/devsm.example-big.toml
"""
tag = ["schema"]

[test.devsm-validate-big-config]
cmd = [
  "cargo",
  "run",
  "--",
  "self",
  "validate",
  "--skip-path-checks",
  "schema/devsm.example-big.toml",
]
require = [{ resource = "cargo-bin" }]
tag = ["schema"]

[test.typos]
cmd = ["typos", "--color", "always"]

[test.check]
cmd = ["cargo", "check"]

[test.cargo-test]
cmd = ["cargo", "test", "--features=fuzz"]
require = [{ resource = "cargo-bin" }]

[test.cargo-build]
cmd = ["cargo", "build"]

[test.completion-bash]
sh = "./tests/completions/bash.test.sh"
require = [{ resource = "cargo-bin" }]
tag = ["completion"]

[test.completion-fish]
sh = "./tests/completions/fish.test.fish"
require = [{ resource = "cargo-bin" }]
tag = ["completion"]

[test.completion-zsh]
sh = "./tests/completions/zsh.test.zsh"
require = [{ resource = "cargo-bin" }]
tag = ["completion"]
